# Generated by Django 2.0.3 on 2018-04-06 17:35

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coment', models.CharField(max_length=512)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='website',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_name', models.CharField(max_length=50)),
                ('website_url', models.CharField(max_length=100)),
                ('website_category', models.CharField(choices=[('COLLEGE', 'college'), ('SHOPING', 'shoping'), ('SPORTS', 'sports')], max_length=100)),
                ('website_description', models.CharField(max_length=200)),
                ('Web_update_date', models.DateField(null=True)),
                ('website_logo', models.FileField(upload_to='static/uploads/')),
                ('website_image', models.FileField(upload_to='static/uploads/')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='webid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.website'),
        ),
    ]
