# Generated by Django 2.0.3 on 2018-04-16 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20180407_0643'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='website',
            name='Web_update_date',
        ),
        migrations.RemoveField(
            model_name='website',
            name='website_image',
        ),
        migrations.AlterField(
            model_name='comment',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='website',
            name='website_category',
            field=models.CharField(choices=[('E-COM', 'E-COM'), ('NEWS', 'NEWS'), ('SOCIAL', 'SOCIAL'), ('SPORTS', 'SPORTS'), ('ACADAMIC', 'ACADAMIC'), ('OTHER', 'OTHER')], max_length=100),
        ),
        migrations.AlterField(
            model_name='website',
            name='website_description',
            field=models.TextField(),
        ),
    ]
