# Generated by Django 2.0.3 on 2018-04-16 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20180416_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='coment',
            field=models.TextField(),
        ),
    ]
